### PR TITLE
Polyfills for IE11

### PR DESCRIPTION
**Pull request by superhighfives**
Added polyfills for [.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) and [.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from), for IE11, taken from MDN.

### CODE REVIEW

**Comment by superhighfives** [comment]
Note to self: run `yarn test` before committing.

**Comment by superhighfives** [comment]
It does break dashboard for IE11, from memory, but I'm not sure how many IE11 users we have. That said, to me I think it'd be worth shipping and then removing once we drop IE11 support (if that hasn't already happened).

**Comment by almonk** [comment]
Shall we close this?

**Comment by superhighfives** [comment]
Fine by me, @almonk. It may be easier to allow people to polyfill on a project by project basis, too. I could add that to the README instead?

**Pull request closed without merging**
